# Generated by Django 2.2.3 on 2019-07-18 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingsGroupMembers',
            new_name='SavingsGroupMember',
        ),
    ]
